language: java
jdk:
  - oraclejdk8
sudo: required
cache:
  directories:
    - $HOME/.m2
install: true
before_script:
  - npm install bower -g
  - bower install
script: mvn install
addons:
  ssh_known_hosts:
  - repo.maven.org